databases:
  - name: sampleapp_amt
    databaseName: sampleapp_amt
    user: sampleapp_amt
    plan: free

services:
  - type: web
    name: sampleapp_amt
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sampleapp_amt
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction