databases:
  - name: sampleapp2_amt_test
    databaseName: ssampleapp2_amt_test
    user: sampleapp2_amt_test
    plan: free

services:
  - type: web
    name: sampleapp2_amt_test
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sampleapp2_amt_test
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction